### ISSUE TITLE
issue retrieving more than 400 pages / 10,000 texts in search

### ISSUE THREAD

**Issue by eyaler** [abartov/bybeconv#100]
for search query with params: ` 'file_format': 'txt', 'page': 1, 'periods': ['revival']`
i get total_count=14884 and i can fetch the data for all pages up to 400 giving 10,000 texts. but for page 401 i get server error 500, thus i cannot get the remaining 4884 texts in this way. (i might be able to break the query to eg sub genres but better if this is just a restriction that can be lifted)

**Comment by damisul** [comment]
Yes, this is a limitation of ElasticSearch. 
See https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-result-window

We can change this limit to greater value, but
- we will still have some limit
- it will increase memory usage and load on server

So I would propose to document this limitation on 10000 (or maybe increase it to some greater value) and keep it as-is.

Personally I didn't expected to see /search endpoint used for fetching huge datasets from our db. 

Now about possible workarounds.

ElasticSearch allows to use different approach to fetch results not based on its index. It is called 'search_after'
https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after  Basically it works simlarily, but instead of specifying start index (in our API we specify page, but actually it is transformed to index offset) we specify offset using values, from last received record on previous page. E.g. if we order records by creation_date and on a previous page last record was from 01/01/2018 we can request next 25 records starting from 01/01/2018

This approach will allow us to iterate over huge datasets, but will not allow us to get arbitrary page by index.

We can implement separate endpoint (or maybe extend search endpoint) for this if neccessary. But I need confirmation from @abartov

**Comment by abartov** [comment]
Yes, we can perhaps add another endpoint. But for now, I've raised the limit enough to include the entire database, so you can proceed.

**Comment by eyaler** [comment]
thanks. the use case was to get all texts (including copyright) divided by period

**Comment by eyaler** [comment]
@abartov i am hitting this again for revival

**Comment by damisul** [comment]
I believe we can close this, as it is addressed in https://github.com/abartov/bybeconv/pull/123

**Comment by eyaler** [comment]
as you now have more than 40000 files, i am getting this again at page 1601 @damisul @abartov

**Comment by eyaler** [comment]
thanks! note to self: this has been updated to 50,000. limit is set here: https://github.com/abartov/bybeconv/blob/master/app/chewy/manifestations_index.rb#L2
