### ISSUE TITLE
Indeterministic logic of updating period in expressions when author's period is changed

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#149]
See https://github.com/abartov/bybeconv/blob/3be119f9d67ece7ed7bc3e1de5849d70772f7a81/app/controllers/authors_controller.rb#L366

If author was updated and his period was changed system updates periods in all expressions where author is author or even translator.

I find this logic error prone:
1) work can have several authors, so in theory one author could be in one period, second in other period. In this case expressions period can be updated wrongly.
2) In a case of translations it is even worse: modern translation of ancient work can be updated to either modern of ancient depending on who was updated last: author or translato.

I don't think there is a 'proper' way to handle such situations.
Perhaps it would be better to drop this logic and maybe add separate admin screen 'inconsistent period' or something like this.

**Comment by abartov** [comment]
Good catch!  

Our notion of 'period' is _only_ relevant to Hebrew literature (other literatures have other periodifications), so, for example, the Hebrew translation of Homer's Iliad that we have should be labelled "revival", because that's the period of the Hebrew _translator_ who created it.

Therefore, I think the logic should be corrected to only update expressions where either the work is originally in Hebrew, or where the updated author is the _translator_ of the work.

The (relatively rare) case of multiple authors or (even rarer) multiple translators is less of a concern, in my opinion, because, first, they would have to be contemporaries to have collaborated on the work/translation, and secondly, the 'period' field in our catalog is a discovery/filtering aid only, not an authoritative literary-historical determination, and is explicitly not an exact science, so I think it's okay even if an expression with multiple authors receives the period of the last-updated author.
