### ISSUE TITLE
Include Collections in search results

### ISSUE THREAD

**Issue by abartov** [abartov/bybeconv#395]
Include and show (certain kinds of) Collections in site-wide search results.

  - Collections should appear *interspersed* with regular Manifestations (probably means they should be indexed in the ManifestationsIndex?)
  - Collections of all types should be indexed, *except* root_collection (deprecated), uncollected, and periodical_issue
  - search results should indicate textified collection type in parenthesis after title (like 'יצירה' for Manifestations today)

**Comment by damisul** [comment]
First of all. I assume, that by 'site-wide search' you mean page allowing to do search among texts, persons and dictionary entries, e.g.: https://benyehuda.org/search/results/?q=test

**Collections should appear interspersed with regular Manifestations (probably means they should be indexed in the ManifestationsIndex?)**

Yes, adding collections to ManifestationsIndex is the first thing which comes to mind, but I'm seeing following drawbacks in this approach:

1. It will require to index same texts several times (as individual text, as part of collection, and probably as part of several other top-level collections). Let's suppose we have text 'Iliada' in collection 'Volume 3', which is included in collection 'Selected Homer Works', which is included in collection 'Ancient authors: Greece and Rome'.

In this case we'll have full Iliada text included in 4 entries 'Iliada', 'Volume 3', 'Selected Homer Works', 'Ancient Authors: Greece and Rome'. And each text in the list is significally longer than previous one. I can imagine collections with total size of dozens megabytes.

Such entries will significally increase size of ManifestationIndex (at least 2 times bigger if we expect all manifestations to be part of some collection in future, but probably even bigger as we expect to have nested collection).

2. Working with such large index entries will cause additional issues. Like this one, we seen while trying to obtain search hint from texts larger than 1 megabyte: https://github.com/abartov/bybeconv/issues/299


As an alternative solution I can propose following.
What if we'll simply display all collections including given text in a list next to manifestation name?

E.g. in an example above we can display:

Iliada [Creation]
included in 
- 'Volume 3' of 'Selected Homer Works' of 'Ancient authors: Greece and Rome'] ?

If item is included in several collections not related to each other we can display a list of collections below:
Iliada [Creation]
included in 
- 'Volume 3' of 'Selected Homer Works' of 'Ancient authors: Greece and Rome'] ?
- 'Selected classical works for highschool students'


This approach should be simpler to implement and will not require any changes to ElasticSearch indices.

What do you think @abartov ?

**Comment by damisul** [comment]
Hm... Ok, I see...

I can propose two different approaches then:

1. We can add 'collection_titles' attribute to ManifestationIndex and store there array of all collections given Manifestation belongs to (including all upper-level collections). And we'll modify search to also check this field. We can display link to collection titles below each Manifestation, just like I proposed above:

```
Iliada [Creation]
included in 
- 'Volume 3' of 'Selected Homer Works' of 'Ancient authors: Greece and Rome']
- 'Selected classical works for highschool students'
```

But in this case there will not be separate entry for each collection in search results. We'll have list of collections for each found manifestation instead. So if we'll look for 'Ancient authors: Greece and Rome' it will include all greece and roman works, included in this collection and/or its subcollections.

One of the benefits of this approach is that we can quite easily utilize it in API and/or in Works search form (e.g. we can add autocomplete field to search form to filter works by collection names)

2. We can create separate CollectionsIndex and store there titles for all collections out there.
In this case we can update multiindex-search to check this new index too and display found collection on search results page together with Manifestations, Dictionaries and Authorities.

The problem here is that multiindex-search sorts results by indices.
Currently it sorts them in following order: Authorities, Manifestations, Dicts (see https://github.com/abartov/bybeconv/pull/382)
We can make it to e.g. show collections before (or after) Manifestations, but I'm not sure if it can be described as '_Collections should appear interspersed with regular Manifestations_'.


-------------
I can also propose additional option:

3. I remeber few months ago we discussed possibility of massive refactoring of Site-wide search and update it to use e.g. different tabs for each content type. So in search result form we'd have three tabs:
- Manifestations
- Authorities
- Dicts

If we'll go this way we can simply add there a fourth tab to show collections sorted by title.

**Comment by abartov** [comment]
Option 2 is not useful -- the distinction between texts and collections is important in other contexts, but in search results, we wouldn't want to see all collections before/after all texts.

The problem I see with option 1 is that if I looked for <collection_title>, it is making me click on a result called <work_title>, which logically should lead to the work and not to the collection. It would also present N results, for the N works included in the collection, which litters the result set needlessly.

Is there not the option I envisioned, of indexing Collection titles as shallow ManifestationIndex entities, with just a title and a null or empty body text and other attributes?  That way, they are presented as first-order search results, once, and are clickable leading, as expected, to Collection#show.

**Comment by abartov** [comment]
Tabbed results are a possible way to go, but we need to think about it from UX/usability perspective, and we are not ready to do that at the moment - our UX expert is not available for a few weeks - so for now that's not the solution we need.

**Comment by damisul** [comment]
> Is there not the option I envisioned, of indexing Collection titles as shallow ManifestationIndex entities, with just a title and a null or empty body text and other attributes? That way, they are presented as first-order search results, once, and are clickable leading, as expected, to Collection#show.

We we can do it too. But there are some problems with this:
- first of all it is kind of misleading for developers to have non-manifestation records in ManifestationsIndex
- we'll need to add additional field to ManifestationIndex like record_type to distinquish records created for Manifestations and for Collections
- we'll need to update all places where ManifestaionIndex is used to filter-out records representing collections (a lot of unwanted side-effects possible without this)
- I still not sure how Elastic will sort such 'fake' records compared to 'normal manifestations'. I believe 'query' should order by 'relevance' (i.e. computed _score field), but I'm not sure how it will be calculated.

On the other hand I can use approach 2. and try to sort all 'Manifestations' and 'Collections' records using their '_score' so they will be somehow 'interleaved'. It *probably* should be doable using script-based ordering we already use there.

**Comment by damisul** [comment]
from telegram:

> Asaf Bartov, [26.11.2024 21:51]
okay, please explore option 2 with interleaved results.

> Asaf Bartov, [26.11.2024 21:51]
boosting should be such that searching for X where there is a collection titled X would show that collection at or near the top.

> Asaf Bartov, [26.11.2024 21:53]
(i.e. even if some *texts* contain a lot of X in their markdown bodies)
