### ISSUE TITLE
Refactor involved_authorities editing UI for easier reuse in Collection

### ISSUE THREAD

**Issue by damisul** [abartov/bybeconv#416]
Currently we can only edit involved authorities on Work and Expression level from /manifestations/edit_metadata form:
![изображение](https://github.com/user-attachments/assets/d1cb7573-edd7-47d5-85f9-6744ede5a459)

I'd like to reuse this UI in Collection CRUD form (see https://github.com/abartov/bybeconv/issues/409)
The problem is that old implementation is tied to manifestation editing form.

So I'd like to extract this and modify in more resuable form (move creation of InvolvedAuthorities from Manifestation#update action to InvolvedAuthorities controller and make it more flexible) so it will change manifestations/edit_metadata page as well.

P.S. Frankly speaking I'd like to use React to achieve this. I believe it could be a good demonstation on how React allows to simplify UI code and create reusable components. But for now I can do it with plain js/jQuery.

**Comment by damisul** [comment]
I also propose to use autocomplete field to fetch authorities (currently it loads whole array of authorities into a drop-down)

**Comment by abartov** [comment]
Yes, this is a good idea. Please do refactor.  And yes, autocomplete (also querying the aliases in the additional names field!) would make sense at this point, instead of loading the whole table.

I am hesitant to add React to the project with the limited funding we have for your time. I would welcome revisiting that decision when we secure a larger grant that would enable more sustained work, including on infrastructure.
